project:
  type: website
  output-dir: docs

website:
  title: "StratoBayes"
  page-navigation: false
  sidebar:
    style: "docked"
    search: true
    logo: "images/logo-2.png"
    contents:
      - text: "Home"
        href: https://stratobayes.github.io/
      - text: "Software"
        href: index.qmd
      - text: "Website"
        href: https://stratobayes.com
      - text: "Workshop"
        href: https://stratobayes.github.io/workshop
      # - section: "Content"
        # contents:
        #   - day1.qmd
        #   - day2.qmd
        #   - day3.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

